spring:
   datasource:
      master:
         jdbc-url: jdbc:mysql://localhost:3306/study?serverTimezone=GMT%2B8
         username: root
         password: 123456
         driver-class-name: com.mysql.jdbc.Driver
      slave:
         jdbc-url: jdbc:mysql://localhost:3307/study?serverTimezone=GMT%2B8
         username: root
         password: 123456
         driver-class-name: com.mysql.jdbc.Driver
         